name: Avalonia Desktop Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Viktor/Nemetschek_Exercise/Avalonia/Filmify

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build .NET project
        run: dotnet build --configuration Release

      - name: Publish .NET project
        run: dotnet publish --configuration Release --output build_output

      - name: Upload build artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: release-dlls
          path: D:\a\Training-Program\Training-Program\Viktor\Nemetschek_Exercise\Avalonia\Filmify\build_output\*.dll