name: Avalonia Desktop Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Viktor/Nemetschek_Exercise/Avalonia/Filmify

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build .NET project
        run: dotnet build --configuration Release

      - name: Publish .NET project
        run: dotnet publish --configuration Release --output build_output
      
      - name: Create Release
        id: create_release
        run: |
          tag_name="Filmify"
          asset_path="build_output"
          body="Release notes here"
          gh release create "$tag_name" "$asset_path/*" --notes "$body"