name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2

      - name: Build application
        run: dotnet build --configuration Release
        working-directory: Viktor/Nemetschek_Exercise/Avalonia/Filmify

      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Filmify
          title: Release Filmify